version: '3.9'
services:
  admin:
    build: './admin'

  builder:
    build: './builder'

  nginx-gateway:
    build: './nginx-gateway'
    ports:
      - 80:80
    depends_on:
      - admin
      - builder

  core-db:
    build:
      context: ./
      dockerfile: './core-db/Dockerfile'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=database
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: